language: python

python:
  - "3.5"
  - "3.6"

install:
  - "pip install -r requirements.txt"
  - "pip install flake8"

script:
- "flake8 --count --exclude ./service_study/migrations,./service_main/migrations,./accounts/migrations,./manage.py,./study_hard/settings.py"
