version: '2'
services:
  nginx:
    build: ./nginx
    networks:
      - backend
      - frontend
    ports:
      - "80:80"
    links:
      - daphne
    depends_on:
      - daphne
      - worker
    environment:
      DAPHNE_HOST: daphne
    volumes_from:
      - daphne
  postgres:
      image: postgres
      environment:
        - POSTGRES_USER=studyadmin
        - POSTGRES_PASSWORD=temporary@P@SSW0rD
        - POSTGRES_DB=studyhard
      volumes:
        - ./postgres:/docker-entrypoint-initdb.d:ro
        - ./postgres_db:/var/lib/postgresql/data:rw
      networks:
        - backend
      ports:
        - "5432:5432"
  redis:
      image: redis
      networks:
        - backend
      ports:
        - "6379:6379"
  worker:
      build: .
      working_dir: /opt/study-hard
      command: bash -c "python manage.py runworker"
      environment:
        - REDIS_HOST=redis
        - POSTGRES_HOST=postgres
      networks:
        - frontend
        - backend
      depends_on:
        - redis
        - postgres
      links:
        - redis
        - postgres
  daphne:
      build: .
      working_dir: /opt/study-hard
      command: bash -c "daphne -b 0.0.0.0 -p 8000 study_hard.asgi:channel_layer"
      ports:
        - "8000:8000"
      environment:
        - REDIS_HOST=redis
        - POSTGRES_HOST=postgres
        - IS_HTTPS_IN_FRONT_OF_NGINX=False
      networks:
        - frontend
        - backend
      depends_on:
        - redis
        - postgres
      links:
        - redis
        - postgres
      volumes:
        - /opt/study-hard/collected_static
networks:
  frontend: # exposed
  backend: # not exposed
